export const texts = {
  brand: "تمرکزسنج",
  seo: {
    title: "سنجش تمرکز و پرسشنامه ADHD",
    description:
      "یک غربالگری خودگزارش‌کننده به زبان فارسی که آزمون تمرکز کوتاه را با تحلیل هوش مصنوعی ترکیب می‌کند. این سرویس جایگزین تشخیص پزشکی نیست.",
  },
  nav: {
    start: "شروع سنجش",
  },
  landing: {
    badge: "غربالگری، نه تشخیص پزشکی",
    heroTitle: "آزمون تمرکز و پرسشنامه ADHD برای خودارزیابی آگاهانه",
    heroSubtitle:
      "در کمتر از ده دقیقه با چند پرسش کوتاه و آزمون واکنش ساده، الگوی توجه خود را بررسی کن. گزارش نهایی فقط برای درک شخصی است و جای مشاوره تخصصی را نمی‌گیرد.",
    ctaPrimary: "همین حالا شروع کن",
    stats: {
      focusLabel: "شاخص‌های تمرکز",
      focusValue: "۴+",
      focusDescription: "دقت، میانگین واکنش، نوسان واکنش و خطاها",
      reportLabel: "بخش‌های گزارش",
      reportValue: "۶",
      reportDescription: "نمای کلی، نقاط قوت، چالش‌ها و پیشنهادهای عملی",
    },
    reportPreview: {
      title: "نمونه گزارش",
      description:
        "نمودارهای واضح به همراه خلاصه‌ای به زبان ساده. خروجی PDF و لینک اشتراکی نیز در دسترس است.",
      gaugeLabel: "بازه ریسک کلی",
      checklist: [
        "نمای کلی وضعیت توجه",
        "نقاط قوت رفتاری",
        "چالش‌های احتمالی",
        "پیشنهادهای کاربردی",
        "نشانه‌های نیاز به ارجاع تخصصی",
      ],
    },
    features: [
      {
        title: "پرسشنامه بومی",
        description: "گویه‌های سفارشی که می‌توانند توسط تیم شما ویرایش شوند.",
      },
      {
        title: "آزمون تمرکز کوتاه",
        description: "آزمون Go/No-Go دو دقیقه‌ای با تحلیل خطا و واکنش.",
      },
      {
        title: "روایت هوش مصنوعی",
        description: "جمع‌بندی ساخت‌یافته توسط AvalAI فقط در محیط سرور.",
      },
      {
        title: "تأکید بر ایمنی",
        description: "توضیحات متعدد مبنی بر این‌که خروجی تشخیص پزشکی نیست.",
      },
    ],
  },
  footer: {
    crisis:
      "این ابزار صرفاً برای خودارزیابی است. اگر در بحران هستید یا عملکرد روزمره شما مختل شده است، با اورژانس یا درمانگر مجاز تماس بگیرید.",
  },
  startPage: {
    badge: "گام اول · رضایت آگاهانه",
    title: "قبل از شروع چه می‌آموزی؟",
    description:
      "با پاسخ به چند پرسش و سپس یک آزمون تمرکز کوتاه، الگوی توجه خود را بهتر می‌شناسی. نتیجه فقط برای گفت‌وگو با متخصص کاربرد دارد.",
    highlights: [
      {
        title: "پرسشنامه ADHD",
        description: "گویه‌های کوتاه در دو خرده‌مقیاس بی‌توجهی و بیش‌فعالی/تکانشگری.",
      },
      {
        title: "آزمون تمرکز",
        description: "Go/No-Go با تحلیل دقت، خطای انجام و خطای حذف.",
      },
      {
        title: "روایت فارسی",
        description: "AvalAI خلاصه‌ای همدلانه و غیرتشخیصی تولید می‌کند.",
      },
    ],
    consentTitle: "حریم خصوصی و رضایت",
    consentDescription:
      "برای تولید گزارش، پاسخ‌ها به صورت ناشناس ذخیره می‌شود. وارد کردن ایمیل اختیاری است و صرفاً برای ارسال لینک استفاده خواهد شد.",
  },
  startForm: {
    emailLabel: "ایمیل (اختیاری)",
    emailPlaceholder: "مثلاً you@example.com",
    emailHint: "در صورت تمایل می‌توانی لینک گزارش را در ایمیلت نگه داری.",
    consentLabel: "می‌دانم این غربالگری جایگزین تشخیص حرفه‌ای نیست.",
    consentDescription: "پاسخ‌ها ناشناس ذخیره می‌شود و فقط برای گزارش شخصی کاربرد دارد.",
    submit: "شروع ارزیابی",
    error: "لطفاً گزینه رضایت را تیک بزن و اگر ایمیل وارد می‌کنی معتبر باشد.",
  },
  focusTest: {
    instructions:
      "وقتی نماد هدف نمایش داده شد (حرف مشخص‌شده)، کلید فاصله را فقط برای آن فشار بده و برای نماد غیرهدف هیچ کاری نکن. آزمون حدود دو دقیقه طول می‌کشد.",
    start: "شروع آزمون تمرکز",
    trialsLabel: "آیتم",
    pressSpace: "کلید فاصله را فقط روی هدف فشار بده",
    completed: "آزمون تمرکز به پایان رسید",
    summary: (metrics: { accuracy: string; reaction: string; variability: string }) =>
      `دقت ${metrics.accuracy}٪ · میانگین واکنش ${metrics.reaction} میلی‌ثانیه · نوسان ${metrics.variability} میلی‌ثانیه`,
    saving: "در حال ذخیره نتایج",
    error: "ذخیره آزمون تمرکز انجام نشد؛ می‌توانی دوباره تلاش کنی یا از این مرحله بگذری.",
    skip: "فعلاً از آزمون تمرکز می‌گذرم",
  },
  assessment: {
    steps: ["پرسشنامه", "آزمون تمرکز", "نتیجه"],
    saveAnswers: "ثبت پاسخ‌ها",
    focusDescription:
      "پس از آزمون تمرکز می‌توانی گزارش ترکیبی را فعال کنی. گذر از این مرحله آزاد است ولی توصیه می‌شود انجام شود.",
    generateTitle: "ساخت گزارش",
    generateDescription:
      "نمره‌های خرده‌مقیاس و آزمون تمرکز به همراه روایت فارسی ترکیب می‌شود.",
    generateButton: "ساخت گزارش شخصی",
    generating: "در حال ساخت گزارش...",
    chartTitle: "نمره خرده‌مقیاس‌ها",
    focusChartTitle: "پراکندگی زمان واکنش",
    successTitle: "گزارش آماده است",
    successMsg: "برای مشاهده جزئیات روی دکمه زیر بزن.",
    viewReport: "نمایش گزارش کامل",
    error: "ذخیره پاسخ‌ها انجام نشد. لطفاً دوباره تلاش کن.",
    completeError: "ساخت گزارش با خطا مواجه شد. چند دقیقه بعد دوباره امتحان کن.",
  },
  report: {
    badge: "گزارش غربالگری",
    title: "خلاصه شخصی تمرکز و توجه",
    completedAt: (date: string) => `تکمیل‌شده در ${date}`,
    downloadPdf: "دریافت PDF",
    copyLink: "کپی لینک گزارش",
    copied: "لینک کپی شد",
    questionnaireCard: "خرده‌مقیاس‌های پرسشنامه",
    riskCard: "برآورد کلی",
    focusCard: "شاخص‌های آزمون تمرکز",
    narrativeCard: "روایت هوش مصنوعی",
    missingNarrative: "روایت هنوز ساخته نشده است. چند دقیقه بعد دوباره تلاش کن تا نسخه کامل در دسترس قرار گیرد.",
    disclaimerTitle: "سلب مسئولیت",
    disclaimerBody:
      "این گزارش یک ابزار آموزشی و خودگزارش است. برای تشخیص یا درمان با روان‌پزشک یا روان‌شناس مجاز گفت‌وگو کن.",
    percentLabel: "درصد",
    pendingRisk: "در حال بررسی",
  },
  share: {
    copy: "کپی لینک گزارش",
    copied: "کپی شد",
  },
  admin: {
    layout: {
      title: "کنترل داده",
      dashboard: "نمای کلی",
      questionnaires: "پرسشنامه‌ها",
      prompts: "الگوهای روایت",
      sessions: "نشست‌ها",
      settings: "تنظیمات",
      signOut: "خروج",
    },
    login: {
      title: "ورود مدیر سامانه",
      description: "دسترسی فقط برای تیم درمانی مجاز است.",
      email: "ایمیل",
      password: "رمز عبور",
      submit: "ورود",
      error: "نام کاربری یا رمز عبور درست نیست.",
    },
    dashboard: {
      welcome: "گزارش سریع",
      subtitle: "کارکرد سامانه را رصد کن و در صورت نیاز روایت‌ها را به‌روزرسانی کن.",
      stats: {
        totalSessions: "کل نشست‌ها",
        completionRate: "نرخ تکمیل",
        avgScore: "میانگین نمره",
        reports: "گزارش‌های این هفته",
      },
      table: {
        title: "آخرین نشست‌ها",
        session: "شناسه",
        status: "وضعیت",
        questionnaire: "پرسشنامه",
        date: "زمان",
      },
    },
    questionnaires: {
      title: "مدیریت پرسشنامه",
      subtitle: "گویه‌ها و قوانین نمره‌گذاری را تنظیم کن.",
      createTitle: "ساخت پرسشنامه جدید",
      fields: {
        title: "عنوان",
        description: "توضیح",
        publish: "انتشار فوری",
        save: "ذخیره",
        questionText: "متن سؤال",
        subscale: "خرده‌مقیاس",
        order: "ترتیب",
        reverse: "نمره‌دهی معکوس",
        addQuestion: "افزودن سؤال",
        scoring: "قوانین نمره‌گذاری",
        method: "روش (sum یا average)",
        scaleMin: "حداقل مقیاس",
        scaleMax: "حداکثر مقیاس",
        itemsPlaceholder: "آیتم‌های JSON",
        thresholdsPlaceholder: "آستانه‌ها به‌صورت JSON",
        saveRule: "ذخیره قانون",
      },
      questionMeta: (subscale: string, order: number) => `${subscale || "بدون خرده‌مقیاس"} · ترتیب ${order}`,
    },
    prompts: {
      title: "مدیریت الگوهای روایت",
      subtitle: "نسخه‌های مختلف متن سیستم و کاربر را کنترل کن.",
      newVersion: "نسخه جدید",
      name: "نام الگو",
      activate: "فعال‌سازی",
      systemPrompt: "پرامپت سیستم",
      userTemplate: "قالب کاربر (متغیرها قابل استفاده هستند)",
      save: "ذخیره نسخه",
      previewLabel: "پیش‌نمایش با نشست",
      dryRun: "تولید آزمایشی",
    },
    sessions: {
      title: "نشست‌ها",
      subtitle: "فیلتر، خروجی CSV و بازسازی روایت از این قسمت انجام می‌شود.",
      searchPlaceholder: "جستجو بر اساس شناسه، ایمیل یا بازه ریسک",
      search: "جستجو",
      export: "خروجی CSV",
      table: {
        id: "شناسه",
        status: "وضعیت",
        risk: "بازه ریسک",
        questionnaire: "پرسشنامه",
        completedAt: "زمان تکمیل",
        actions: "اقدامات",
        view: "نمایش گزارش",
        regenerate: "بازسازی روایت",
      },
    },
    settings: {
      appTitle: "تنظیمات عمومی",
      focusTitle: "آزمون تمرکز",
      auditTitle: "لاگ تغییرات",
      allowEmail: "امکان ثبت ایمیل کاربران",
      focusOptional: "امکان رد آزمون تمرکز",
      shareLinks: "لینک اشتراک گزارش",
      defaultLanguage: "زبان پیش‌فرض",
      disclaimer: "متن سلب مسئولیت",
      saveApp: "ذخیره تنظیمات عمومی",
      duration: "مدت آزمون (ثانیه)",
      frequency: "فاصله نمایش نماد (میلی‌ثانیه)",
      ratio: "نسبت هدف",
      targetSymbol: "نماد هدف",
      nonTargetSymbol: "نماد غیرهدف",
      saveFocus: "ذخیره تنظیمات آزمون",
    },
  },
};
